// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBovXwXj8AdviTGlIEZRGmuOc0ALg_9fRY',
    appId: '1:481897753925:web:9fe6203acc61681544222c',
    messagingSenderId: '481897753925',
    projectId: 'water-tech-5d614',
    authDomain: 'water-tech-5d614.firebaseapp.com',
    storageBucket: 'water-tech-5d614.appspot.com',
    measurementId: 'G-V17ZP2CPX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVGE971Sw5oUIZMfZp7lIueT34y-UZ-Eg',
    appId: '1:481897753925:android:50804e33eb19f32644222c',
    messagingSenderId: '481897753925',
    projectId: 'water-tech-5d614',
    storageBucket: 'water-tech-5d614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs82d6r07adr_7uzcAdCE_GkZddxxVZk4',
    appId: '1:481897753925:ios:619079a36bb5d9d844222c',
    messagingSenderId: '481897753925',
    projectId: 'water-tech-5d614',
    storageBucket: 'water-tech-5d614.appspot.com',
    iosBundleId: 'com.example.waterTech',
  );
}
